# Generated by Django 3.2.7 on 2021-12-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(default='P', max_length=3),
        ),
    ]
